name: bookstore

on:
  push:
    branches:
      - dev

jobs:
  deployment:
    runs-on: self-hosted
    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Update Lockfile
        run: npm install --omit=dev

      - name: Install dependencies
        run: npm ci --omit=dev
 

      - name: Start server application
        run: npm run dev


